### ISSUE TITLE
Separate Sensors for Gas / Electricity?

### ISSUE THREAD

**Issue by totalitarian** [danmed/Glow2MQTT#2]
Love this script. Anyway to get the sensors separated into elec / gas?

**Comment by danmed** [comment]
yeah you can, pyglowmarkt allows for gas consumption to be collected too.

for example : 

`/usr/local/bin/glowmarkt-mqtt -u $glowuser -p $glowpass -c gas.consumption -t $mqtttopic_consumption --host $mqttip --mqtt-username $mqttuser --mqtt-pass $mqttpass`

**Comment by danmed** [comment]
I've updated the consumption.sh to do gas readings too.
